### ISSUE TITLE
MTAdmob 1.0.4 is conflicting with Plugin.Firebase 1.2.5

### ISSUE THREAD

**Issue by eyeveye** [marcojak/MauiMTAdmob#39] opened 2023-08-21 08:47 UTC
On Android, I upgraded 1.0.2 to 1.0.4 an error will be thrown. I found out is the Plugin.Firebase 1.2.5 that has a conflict with 1.0.4.

Reverting it back to 1.0.2, clear the BIN and OBJ will work again.

Here is the error:
```

Severity	Code	Description	Project	File	Line	Suppression State
Error	JAVA0000	Error in obj\Debug\net7.0-android\lp\314\jl\classes.jar:com/google/android/gms/measurement/internal/zzfj.class:
Type com.google.android.gms.measurement.internal.zzfj is defined multiple times: obj\Debug\net7.0-android\lp\314\jl\classes.jar:com/google/android/gms/measurement/internal/zzfj.class, obj\Debug\net7.0-android\lp\315\jl\classes.jar:com/google/android/gms/measurement/internal/zzfj.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\net7.0-android\lp\314\jl\classes.jar
com/google/android/gms/measurement/internal/zzfj.class
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
	at com.android.tools.r8.D8.main(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\net7.0-android\lp\314\jl\classes.jar:com/google/android/gms/measurement/internal/zzfj.class
	at Version.fakeStackEntry(Version_3.3.75.java:0)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:75)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:27)
	at com.android.tools.r8.internal.Fj.b(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:2)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:17)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:85)
	... 1 more
Caused by: com.android.tools.r8.internal.f: Type com.google.android.gms.measurement.internal.zzfj is defined multiple times: obj\Debug\net7.0-android\lp\314\jl\classes.jar:com/google/android/gms/measurement/internal/zzfj.class, obj\Debug\net7.0-android\lp\315\jl\classes.jar:com/google/android/gms/measurement/internal/zzfj.class
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:14)
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:33)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:6)
	at com.android.tools.r8.graph.B2$a.e(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:110)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:25)
	at com.android.tools.r8.D8.d(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:606)
	at com.android.tools.r8.D8.c(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:1)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:24)
	... 5 more
Directory 'obj\Debug\net7.0-android\lp\314' is from 'play-services-measurement-base.aar'.	SGPool.Maui		1	
```

**Comment by neelpanchal52** [comment] 2023-10-24 06:01
same error here, how to solve this?

**Comment by Xoben** [comment] 2023-11-14 17:39
same here.... anyone solve this problem?

**Comment by maliksuhail** [comment] 2024-04-03 05:03
did anyone find solution, i am trying since last year but could not resolve this issue, no metter what the version is. @marcojak should come up with solution. only he can resolve this issue.

**Comment by maliksuhail** [comment] 2024-04-27 15:02
Dear @marcojak , Here is Error details with project file references
----------

Error
-------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error	JAVA0000	Error in obj\Release\net7.0-android\lp\307\jl\classes.jar:com/google/android/gms/internal/measurement/zzia.class:
Type com.google.android.gms.internal.measurement.zzia is defined multiple times: obj\Release\net7.0-android\lp\307\jl\classes.jar:com/google/android/gms/internal/measurement/zzia.class, obj\Release\net7.0-android\lp\309\jl\classes.jar:com/google/android/gms/internal/measurement/zzia.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Release\net7.0-android\lp\307\jl\classes.jar
com/google/android/gms/internal/measurement/zzia.class
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
	at com.android.tools.r8.D8.main(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Release\net7.0-android\lp\307\jl\classes.jar:com/google/android/gms/internal/measurement/zzia.class
	at Version.fakeStackEntry(Version_3.3.75.java:0)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:75)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:27)
	at com.android.tools.r8.internal.Fj.b(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:2)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:17)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:85)
	... 1 more
Caused by: com.android.tools.r8.internal.f: Type com.google.android.gms.internal.measurement.zzia is defined multiple times: obj\Release\net7.0-android\lp\307\jl\classes.jar:com/google/android/gms/internal/measurement/zzia.class, obj\Release\net7.0-android\lp\309\jl\classes.jar:com/google/android/gms/internal/measurement/zzia.class
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:14)
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:33)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2056)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:6)
	at com.android.tools.r8.graph.B2$a.e(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:110)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:25)
	at com.android.tools.r8.D8.d(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:606)
	at com.android.tools.r8.D8.c(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:1)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:24)
	... 5 more
Directory 'obj\Release\net7.0-android\lp\307' is from 'play-services-measurement-base.aar'.	LatestMobilePrices		1	

-------------
other references
---------
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="5.3.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="6.0.0" />
		<PackageReference Include="Plugin.Firebase" Version="2.0.5" />
		<PackageReference Include="Xamarin.Google.Guava" Version="31.1.0.3" />
		<PackageReference Include="Xamarin.Google.Guava.ListenableFuture" Version="9999.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
    <GoogleServicesJson Include="google-services.json" />
</ItemGroup>
----------------
Plugin.MauiMTAdmob reference
---------
	<ItemGroup>
		<PackageReference Include="Plugin.MauiMTAdmob" Version="1.4.1" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
		<PackageReference Include="Xamarin.AndroidX.Activity" Version="1.8.2" />
		<PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.8.2" />
		<PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.6.2.3" />
	</ItemGroup>

**Comment by marcojak** [comment] 2024-06-18 22:22
Is this still an issue?
If not, I'll close it

**Comment by maliksuhail** [comment] 2024-06-20 03:39
Dear @marcojak this is still an issue. 2 Months ago you asked for error details which i posted on next day, you can have a look at my last comment but sadly i did not get any reply from your side. i am facing this issue since last year, i will deeply appreciate your reply regarding my error.

**Comment by Xoben** [comment] 2024-06-20 13:53
I no longer have the issue thx
________________________________

**Comment by maliksuhail** [comment] 2024-06-21 05:53
@Xoben can you please mention, how did you solve that issue. I will deeply appreciate.

**Comment by marcojak** [comment] 2024-08-23 20:02
I'm closing as we are now at version 1.6.
If there are other issues, please open a new one.

**Closed by marcojak** 2024-08-23 20:02 UTC
